# This workflow will scrap GitHub trending projects daily.

name: Monthly Github Trending Archive

on:
  schedule:
    - cron: "0 0 1 * *"
  # workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      run: |
        python arcived_month.py

    # Runs a set of commands using the runners shell
    - name: Push to origin master
      run: |
        echo start push
        git config --global user.name "zengzzzzz"
        git config --global user.email "mrzengzzzz@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
        
